### ISSUE TITLE
Support for Layers

### ISSUE THREAD

**Issue by jstarcher** [localstack/aws-sam-cli-local#3]
It seems samlocal currently cannot handle layers, it fails on my `AWS::Serverless::LayerVersion` resource. Any plans to support it?

**Comment by theUltimateZoltan** [comment]
It seems that layers are only supported for pro users: https://docs.localstack.cloud/aws/lambda-layers/

**Comment by MarcelStranak** [comment]
https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-layers

> Lambda Layers
> [Lambda layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html) lets you include additional code and dependencies in your Lambda functions. With LocalStack Pro/Team, you can deploy Lambda Layers locally to streamline your development and testing process.
